[package]
name = "windows-vscode-gitwrapper"
version = "0.1.0"
authors = ["greatxk <1023052645@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"